nodeLinker: node-modules
# nodeLinker: pnp

# yarn-pnp-configuration:

#   # Enable PnP for the current project
#   enabled: true

#   # Enable PnP for the current project's dependencies
#   dependencies: true

#   # Enable PnP for the current project's devDependencies
#   devDependencies: true

#   # Enable PnP for the current project's peerDependencies
#   peerDependencies: true  

#   # Enable PnP for the current project's optionalDependencies
#   optionalDependencies: true



